version: '3.9'

services:
  server:
    image: lab8:server
    container_name: server
    networks:
      - lab8-network
  client:
    image: lab8:client
    container_name: client
    networks:
      - lab8-network
    environment:
      - SERVER_URL=http://server:3000/users

networks:
  lab8-network:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
